/* SQL commands to create a database for denic RRI*/


CREATE DATABASE denic CHARACTER SET utf8 COLLATE utf8_bin;
CREATE USER 'denic-rri'@'%';
SET PASSWORD FOR 'denic-rri'@'%' = PASSWORD('please-change');
GRANT ALL PRIVILEGES ON denic.* TO 'denic-rri'@'%';
FLUSH PRIVILEGES;

USE `denic`;

DROP TABLE IF EXISTS `country_code`;
CREATE TABLE `country_code` (
  `cc_id` int(255) NOT NULL auto_increment,
  `cc_code` varchar(255) NOT NULL,
  `cc_value` varchar(255) NOT NULL,
  `cc_description` varchar(255) NOT NULL,
  PRIMARY KEY  (`cc_id`)
);

DROP TABLE IF EXISTS `domain`;
CREATE TABLE `domain` (
  `dm_id` int(255) NOT NULL auto_increment,
  `dm_action` varchar(255) default NULL,
  `dm_domain` varchar(66) default NULL,
  `dm_domain_ace` varchar(66) default NULL,
  `dm_holder` varchar(32) default NULL,
  `dm_admin` varchar(32) default NULL,
  `dm_tech` varchar(32) default NULL,
  `dm_zone` varchar(32) default NULL,
  `dm_ns_0` varchar(254) default NULL,
  `dm_ns_1` varchar(254) default NULL,
  `dm_ns_2` varchar(254) default NULL,
  `dm_ns_3` varchar(254) default NULL,
  `dm_key` varchar(999) default NULL,
  `dm_authinfo` tinyint(1) default NULL,
  PRIMARY KEY  (`dm_id`)
);

DROP TABLE IF EXISTS `handle`;
CREATE TABLE `handle` (
  `hd_id` int(255) NOT NULL AUTO_INCREMENT,
  `hd_handle` varchar(32) default NULL,
  `hd_action` varchar(255) default NULL,
  `hd_type` varchar(255) default NULL,
  `hd_name` varchar(255) default NULL,
  `hd_organisation` varchar(255) default NULL,
  `hd_address` varchar(255) default NULL,
  `hd_pcode` varchar(20) default NULL,
  `hd_city` varchar(80) default NULL,
  `hd_country` varchar(2) default NULL,
  `hd_phone` varchar(255) default NULL,
  `hd_fax` varchar(255) default NULL,
  `hd_email` varchar(255) default NULL,
  `hd_sip` varchar(255) default NULL,
  `hd_disclose` varchar(255) default NULL,
  `hd_remarks_0` varchar(255) default NULL,
  `hd_remarks_1` varchar(255) default NULL,
  `hd_remarks_2` varchar(255) default NULL,
  `hd_remarks_3` varchar(255) default NULL,
  PRIMARY KEY  (`hd_id`)
);

INSERT INTO `country_code` VALUES (1,'DE','DE','GERMANY'),
  (2,'AF','AF','AFGHANISTAN'),
  (3,'AX','AX','ÅLAND ISLANDS'),
  (4,'AL','AL','ALBANIA'),
  (5,'DZ','DZ','ALGERIA'),
  (6,'AS','AS','AMERICAN SAMOA'),
  (7,'AD','AD','ANDORRA'),
  (8,'AO','AO','ANGOLA'),
  (9,'AI','AI','ANGUILLA'),
  (10,'AQ','AQ','ANTARCTICA'),
  (11,'AG','AG','ANTIGUA AND BARBUDA'),
  (12,'AR','AR','ARGENTINA'),
  (13,'AM','AM','ARMENIA'),
  (14,'AW','AW','ARUBA'),
  (15,'AU','AU','AUSTRALIA'),
  (16,'AT','AT','AUSTRIA'),
  (17,'AZ','AZ','AZERBAIJAN'),
  (18,'BS','BS','BAHAMAS'),
  (19,'BH','BH','BAHRAIN'),
  (20,'BD','BD','BANGLADESH'),
  (21,'BB','BB','BARBADOS'),
  (22,'BY','BY','BELARUS'),
  (23,'BE','BE','BELGIUM'),
  (24,'BZ','BZ','BELIZE'),
  (25,'BJ','BJ','BENIN'),
  (26,'BM','BM','BERMUDA'),
  (27,'BT','BT','BHUTAN'),
  (28,'BO','BO','BOLIVIA'),
  (29,'BA','BA','BOSNIA AND HERZEGOVINA'),
  (30,'BW','BW','BOTSWANA'),
  (31,'BV','BV','BOUVET ISLAND'),
  (32,'BR','BR','BRAZIL'),
  (33,'IO','IO','BRITISH INDIAN OCEAN TERRITORY'),
  (34,'BN','BN','BRUNEI DARUSSALAM'),
  (35,'BG','BG','BULGARIA'),
  (36,'BF','BF','BURKINA FASO'),
  (37,'BI','BI','BURUNDI'),
  (38,'KH','KH','CAMBODIA'),
  (39,'CM','CM','CAMEROON'),
  (40,'CA','CA','CANADA'),
  (41,'CV','CV','CAPE VERDE'),
  (42,'KY','KY','CAYMAN ISLANDS'),
  (43,'CF','CF','CENTRAL AFRICAN REPUBLIC'),
  (44,'TD','TD','CHAD'),
  (45,'CL','CL','CHILE'),
  (46,'CN','CN','CHINA'),
  (47,'CX','CX','CHRISTMAS ISLAND'),
  (48,'CC','CC','COCOS (KEELING) ISLANDS'),
  (49,'CO','CO','COLOMBIA'),
  (50,'KM','KM','COMOROS'),
  (51,'CG','CG','CONGO'),
  (52,'CD','CD','CONGO, THE DEMOCRATIC REPUBLIC OF THE'),
  (53,'CK','CK','COOK ISLANDS'),
  (54,'CR','CR','COSTA RICA'),
  (55,'CI','CI','COTE D\'IVOIRE'),
  (56,'HR','HR','CROATIA'),
  (57,'CU','CU','CUBA'),
  (58,'CY','CY','CYPRUS'),
  (59,'CZ','CZ','CZECH REPUBLIC'),
  (60,'DK','DK','DENMARK'),
  (61,'DJ','DJ','DJIBOUTI'),
  (62,'DM','DM','DOMINICA'),
  (63,'DO','DO','DOMINICAN REPUBLIC'),
  (64,'EC','EC','ECUADOR'),
  (65,'EG','EG','EGYPT'),
  (66,'SV','SV','EL SALVADOR'),
  (67,'GQ','GQ','EQUATORIAL GUINEA'),
  (68,'ER','ER','ERITREA'),
  (69,'EE','EE','ESTONIA'),
  (70,'ET','ET','ETHIOPIA'),
  (71,'FK','FK','FALKLAND ISLANDS (MALVINAS)'),
  (72,'FO','FO','FAROE ISLANDS'),
  (73,'FJ','FJ','FIJI'),
  (74,'FI','FI','FINLAND'),
  (75,'FR','FR','FRANCE'),
  (76,'GF','GF','FRENCH GUIANA'),
  (77,'PF','PF','FRENCH POLYNESIA'),
  (78,'TF','TF','FRENCH SOUTHERN TERRITORIES'),
  (79,'GA','GA','GABON'),
  (80,'GM','GM','GAMBIA'),
  (81,'GE','GE','GEORGIA'),
  (82,'DE','DE','GERMANY'),
  (83,'GG','GG','GUERNSEY'),
  (84,'GH','GH','GHANA'),
  (85,'GI','GI','GIBRALTAR'),
  (86,'GR','GR','GREECE'),
  (87,'GL','GL','GREENLAND'),
  (88,'GD','GD','GRENADA'),
  (89,'GP','GP','GUADELOUPE'),
  (90,'GU','GU','GUAM'),
  (91,'GT','GT','GUATEMALA'),
  (92,'GN','GN','GUINEA'),
  (93,'GW','GW','GUINEA-BISSAU'),
  (94,'GY','GY','GUYANA'),
  (95,'HT','HT','HAITI'),
  (96,'HM','HM','HEARD ISLAND AND MCDONALD ISLANDS'),
  (97,'VA','VA','HOLY SEE (VATICAN CITY STATE)'),
  (98,'HN','HN','HONDURAS'),
  (99,'HK','HK','HONG KONG'),
  (100,'HU','HU','HUNGARY'),
  (101,'IS','IS','ICELAND'),
  (102,'IN','IN','INDIA'),
  (103,'IM','IM','ISLE OF MAN'),
  (104,'ID','ID','INDONESIA'),
  (105,'IR','IR','IRAN (ISLAMIC REPUBLIC OF)'),
  (106,'IQ','IQ','IRAQ'),
  (107,'IE','IE','IRELAND'),
  (108,'IL','IL','ISRAEL'),
  (109,'IT','IT','ITALY'),
  (110,'JE','JE','JERSEY'),
  (111,'JM','JM','JAMAICA'),
  (112,'JP','JP','JAPAN'),
  (113,'JO','JO','JORDAN'),
  (114,'KZ','KZ','KAZAKHSTAN'),
  (115,'KE','KE','KENYA'),
  (116,'KI','KI','KIRIBATI'),
  (117,'KP','KP','KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF'),
  (118,'KR','KR','KOREA, REPUBLIC OF'),
  (119,'KW','KW','KUWAIT'),
  (120,'KG','KG','KYRGYZSTAN'),
  (121,'LA','LA','LAO PEOPLE\'S DEMOCRATIC REPUBLIC'),
  (122,'LV','LV','LATVIA'),
  (123,'LB','LB','LEBANON'),
  (124,'LS','LS','LESOTHO'),
  (125,'LR','LR','LIBERIA'),
  (126,'LY','LY','LIBYAN ARAB JAMAHIRIYA'),
  (127,'LI','LI','LIECHTENSTEIN'),
  (128,'LT','LT','LITHUANIA'),
  (129,'LU','LU','LUXEMBOURG'),
  (130,'MO','MO','MACAU'),
  (131,'MK','MK','MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF'),
  (132,'MG','MG','MADAGASCAR'),
  (133,'MW','MW','MALAWI'),
  (134,'MY','MY','MALAYSIA'),
  (135,'MV','MV','MALDIVES'),
  (136,'ML','ML','MALI'),
  (137,'MT','MT','MALTA'),
  (138,'MH','MH','MARSHALL ISLANDS'),
  (139,'MQ','MQ','MARTINIQUE'),
  (140,'MR','MR','MAURITANIA'),
  (141,'MU','MU','MAURITIUS'),
  (142,'YT','YT','MAYOTTE'),
  (143,'MX','MX','MEXICO'),
  (144,'FM','FM','MICRONESIA, FEDERATED STATES OF'),
  (145,'MD','MD','MOLDOVA, REPUBLIC OF'),
  (146,'MC','MC','MONACO'),
  (147,'MN','MN','MONGOLIA'),
  (148,'ME','ME','MONTENEGRO'),
  (149,'MS','MS','MONTSERRAT'),
  (150,'MA','MA','MOROCCO'),
  (151,'MZ','MZ','MOZAMBIQUE'),
  (152,'MM','MM','MYANMAR'),
  (153,'NA','NA','NAMIBIA'),
  (154,'NR','NR','NAURU'),
  (155,'NP','NP','NEPAL'),
  (156,'NL','NL','NETHERLANDS'),
  (157,'AN','AN','NETHERLANDS ANTILLES'),
  (158,'NC','NC','NEW CALEDONIA'),
  (159,'NZ','NZ','NEW ZEALAND'),
  (160,'NI','NI','NICARAGUA'),
  (161,'NE','NE','NIGER'),
  (162,'NG','NG','NIGERIA'),
  (163,'NU','NU','NIUE'),
  (164,'NF','NF','NORFOLK ISLAND'),
  (165,'MP','MP','NORTHERN MARIANA ISLANDS'),
  (166,'NO','NO','NORWAY'),
  (167,'OM','OM','OMAN'),
  (168,'PK','PK','PAKISTAN'),
  (169,'PW','PW','PALAU'),
  (170,'PS','PS','PALESTINIAN TERRITORY, OCCUPIED'),
  (171,'PA','PA','PANAMA'),
  (172,'PG','PG','PAPUA NEW GUINEA'),
  (173,'PY','PY','PARAGUAY'),
  (174,'PE','PE','PERU'),
  (175,'PH','PH','PHILIPPINES'),
  (176,'PN','PN','PITCAIRN'),
  (177,'PL','PL','POLAND'),
  (178,'PT','PT','PORTUGAL'),
  (179,'PR','PR','PUERTO RICO'),
  (180,'QA','QA','QATAR'),
  (181,'RE','RE','REUNION'),
  (182,'RO','RO','ROMANIA'),
  (183,'RU','RU','RUSSIAN FEDERATION'),
  (184,'RW','RW','RWANDA'),
  (185,'SH','SH','SAINT HELENA'),
  (186,'KN','KN','SAINT KITTS AND NEVIS'),
  (187,'LC','LC','SAINT LUCIA'),
  (188,'PM','PM','SAINT PIERRE AND MIQUELON'),
  (189,'VC','VC','SAINT VINCENT AND THE GRENADINES'),
  (190,'WS','WS','SAMOA'),
  (191,'SM','SM','SAN MARINO'),
  (192,'ST','ST','SAO TOME AND PRINCIPE'),
  (193,'SA','SA','SAUDI ARABIA'),
  (194,'SN','SN','SENEGAL'),
  (195,'RS','RS','SERBIA'),
  (196,'SC','SC','SEYCHELLES'),
  (197,'SL','SL','SIERRA LEONE'),
  (198,'SG','SG','SINGAPORE'),
  (199,'SK','SK','SLOVAKIA'),
  (200,'SI','SI','SLOVENIA'),
  (201,'SO','SO','SOMALIA'),
  (202,'SB','SB','SOLOMON ISLANDS'),
  (203,'ZA','ZA','SOUTH AFRICA'),
  (204,'GS','GS','SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS'),
  (205,'ES','ES','SPAIN'),
  (206,'LK','LK','SRI LANKA'),
  (207,'SD','SD','SUDAN'),
  (208,'SR','SR','SURINAME'),
  (209,'SJ','SJ','SVALBARD AND JAN MAYEN'),
  (210,'SZ','SZ','SWAZILAND'),
  (211,'SE','SE','SWEDEN'),
  (212,'CH','CH','SWITZERLAND'),
  (213,'SY','SY','SYRIAN ARAB REPUBLIC'),
  (214,'TW','TW','TAIWAN, PROVINCE OF CHINA'),
  (215,'TJ','TJ','TAJIKISTAN'),
  (216,'TZ','TZ','TANZANIA, UNITED REPUBLIC OF'),
  (217,'TH','TH','THAILAND'),
  (218,'TL','TL','TIMOR-LESTE'),
  (219,'TG','TG','TOGO'),
  (220,'TK','TK','TOKELAU'),
  (221,'TO','TO','TONGA'),
  (222,'TT','TT','TRINIDAD AND TOBAGO'),
  (223,'TN','TN','TUNISIA'),
  (224,'TR','TR','TURKEY'),
  (225,'TM','TM','TURKMENISTAN'),
  (226,'TC','TC','TURKS AND CAICOS ISLANDS'),
  (227,'TV','TV','TUVALU'),
  (228,'UG','UG','UGANDA'),
  (229,'UA','UA','UKRAINE'),
  (230,'AE','AE','UNITED ARAB EMIRATES'),
  (231,'GB','GB','UNITED KINGDOM'),
  (232,'US','US','UNITED STATES'),
  (233,'UM','UM','UNITED STATES MINOR OUTLYING ISLANDS'),
  (234,'UY','UY','URUGUAY'),
  (235,'UZ','UZ','UZBEKISTAN'),
  (236,'VU','VU','VANUATU'),
  (237,'VE','VE','VENEZUELA'),
  (238,'VN','VN','VIETNAM'),
  (239,'VG','VG','VIRGIN ISLANDS (BRITISH)'),
  (240,'VI','VI','VIRGIN ISLANDS (U.S.)'),
  (241,'WF','WF','WALLIS AND FUTUNA'),
  (242,'EH','EH','WESTERN SAHARA'),
  (243,'YE','YE','YEMEN'),
  (244,'ZM','ZM','ZAMBIA'),
  (245,'ZW','ZW','ZIMBABWE');